import { createSlice } from "@reduxjs/toolkit";
import paper from "../../public/assets/paper.png";
import cleaning from "../../public/assets/cleaning.png";  
import vacum from "../../public/assets/vacum.png";
import scrubber from "../../public/assets/scrubber.png";
import equipment from "../../public/assets/equipment.png";
import selpak from "../../public/assets/selpak.jpg";
import sens from "../../public/assets/sens.jpg";
import solo from "../../public/assets/solo.jpg";
import selpakExtra from "../../public/assets/selpakExtra.jpg";

const initialState = [
  {
    id: 1,
    title: "Бумажная продукция",
    description: "Туалетная бумага, салфетки, полотенца",
    count: 24,
    image: paper,
    images: [paper, paper, paper, paper],
    link: "бумажная-продукция",
    type: "paper_product",
    catalog:"main",
    singleLink: "туалетная-бумага-салфетки-полотенца",
    popularity: 85,
    price: "25000 UZS"
  },
  {
    id: 2,
    title: "Моющие средства",
    description: "Профессиональная химия для уборки",
    count: 156,
    image: cleaning,
    images: [cleaning, cleaning, cleaning, cleaning],
    link: "моющие-средства",
    type: "cleaning_product",
    catalog:"main",
    singleLink: "профессиональная-химия-для-уборки",
    popularity: 92,
    price: "35000 UZS"
  },
  {
    id: 3,
    title: "Поломоечные машины",
    description: "T55/50B",
    price: "10000 UZS",
    image: scrubber,
    images: [scrubber, scrubber, scrubber, scrubber],
    category: "Поломоечные машины",
    type: "scrubber_product",
    link: "поломоечные-машины/",
    isNew: false,
    catalog:"main",
    count: 8,
    singleLink: "t55-50b",
    popularity: 65
  },
  {
    id: 4,
    title: "Поломоечные машины",
    description: "T35B",
    price: "12000 UZS",
    image: scrubber,
    images: [scrubber, paper, cleaning, scrubber],
    category: "Поломоечные машины",
    type: "scrubber_product",
    link: "поломоечные-машины/",
    isNew: false,
    count: 8,
    singleLink: "t35b",
    popularity: 70,
  },
  {
    id: 5,
    title: "Поломоечные машины",
    description: "T55/50BT",
    price: "15000 UZS",
    image: scrubber,
    images: [scrubber, scrubber, scrubber, scrubber],
    category: "Поломоечные машины",
    type: "scrubber_product",
    link: "поломоечные-машины",
    isNew: false,
    count: 8,
    singleLink: "t55-50bt",
    popularity: 75,
  
  },
  {
    id: 6,
    title: "Поломоечные машины",
    description: "T45/50B",
    price: "16000 UZS",
    oldPrice: "18000 UZS",
    image: scrubber,
    images: [scrubber, scrubber, scrubber, scrubber],
    category: "Поломоечные машины",
    type: "scrubber_product",
    link: "поломоечные-машины/",
    isNew: true,
    count: 8,
    singleLink: "t45-50b",
    popularity: 80
  },
  {
    id: 7,
    title: "Пылесосы",
    description: "Промышленные пылесосы",
    count: 42,
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    link: "пылесосы",
    type: "vacuum_product",
    catalog:"main",
    singleLink: "промышленные-пылесосы",
    popularity: 90,
    price: "40000 UZS"
  },
  {
    id: 8,
    title: "Уборочный инвентарь",
    description: "Швабры, ведра, тележки",
    count: 85,
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    link: "уборочный-инвентарь",
    type: "equipment_product",
    catalog:"main",
    singleLink: "швабры-ведра-тележки",
    popularity: 88,
    price: "30000 UZS"
  },
  {
    id: 9,
    title: "Бумажная продукция",
    description: "Selpak Professional Extra Z-Сложенное полотенце для диспенсера",
    price: "12000 UZS",
    image: selpakExtra,
    images: [selpakExtra, selpakExtra, selpakExtra, selpakExtra],
    category: "БУМАЖНАЯ ПРОДУКЦИЯ",
    type: "paper_product",
    link: "бумажная-продукция",
    isNew: false,
    count: 24,
    singleLink: "selpak-professional-extra-z-сложенное-полотенце-для-диспенсера",
    popularity: 82
  },
  {
    id: 10,
    title: "Бумажная продукция",
    description: "Sens Туалетная бумага 24 шт.",
    price: "15000 UZS",
    image: sens,
    images: [sens, sens, sens, sens],
    category: "БУМАЖНАЯ ПРОДУКЦИЯ",
    type: "paper_product",
    link: "бумажная-продукция",
    isNew: false,
    count: 24,
    singleLink: "sens-туалетная-бумага-24-шт",
    popularity: 85
  },
  {
    id: 11,
    title: "Бумажная продукция",
    description: "Solo Professional 1/6 Складные салфетки Официант 26.5×33 см 100 шт.",
    price: "18000 UZS",
    image: solo,
    images: [solo, solo, solo, solo],
    category: "БУМАЖНАЯ ПРОДУКЦИЯ",
    type: "paper_product",
    link: "бумажная-продукция",
    isNew: false,
    count: 24,
    singleLink: "solo-professional-1-6-складные-салфетки-официант-26-5x33-см-100-шт",
    popularity: 87
  },
  {
    id: 12,
    title: "Бумажная продукция",
    description: "Selpak Professional Extra Туалетная бумага 24 шт.",
    price: "20000 UZS",
    image: selpak,
    images: [selpak, selpak, selpak, selpak],
    category: "БУМАЖНАЯ ПРОДУКЦИЯ",
    type: "paper_product",
    link: "бумажная-продукция",
    isNew: true,
    count: 24,
    singleLink: "selpak-professional-extra-туалетная-бумага-24-шт",
    popularity: 89
  },
  {
    id: 13,
    title: "Моющие средства",
    description: "Maratem M106 5L",
    price: "25000 UZS",
    image: cleaning,
    images: [cleaning, cleaning, cleaning, cleaning],
    category: "МОЮЩИЕ СРЕДСТВА",
    type: "cleaning_product",
    link: "моющие-средства",
    isNew: false,
    count: 156,
    singleLink: "maratem-m106-5l",
    popularity: 91
  },
  {
    id: 14,
    title: "Моющие средства",
    description: "Maratem M107 5l",
    price: "28000 UZS",
    image: cleaning,
    images: [cleaning, cleaning, cleaning, cleaning],
    category: "МОЮЩИЕ СРЕДСТВА",
    type: "cleaning_product",
    link: "моющие-средства",
    isNew: false,
    count: 156,
    singleLink: "maratem-m107-5l",
    popularity: 93
  },
  {
    id: 15,
    title: "Моющие средства",
    description: "Maratem M201 700",
    price: "32000 UZS",
    oldPrice: "35000 UZS",
    image: cleaning,
    images: [cleaning, cleaning, cleaning, cleaning],
    category: "МОЮЩИЕ СРЕДСТВА",
    type: "cleaning_product",
    link: "моющие-средства",
    isNew: true,
    count: 156,
    singleLink: "maratem-m201-700",
    popularity: 95
  },
  {
    id: 16,
    title: "Пылесосы",
    description: "Пылесос для сухой уборки NT 30/1 Tact L",
    price: "45000 UZS",
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    category: "ПЫЛЕСОСЫ",
    type: "vacuum_product",
    link: "пылесосы",
    isNew: false,
    count: 42,
    singleLink: "пылесос-для-сухой-уборки-nt-30-1-tact-l",
    popularity: 97
  },
  {
    id: 17,
    title: "Пылесосы",
    description: "Пылесос для сухой и влажной уборки NT 70/2",
    price: "52000 UZS",
    oldPrice: "55000 UZS",
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    category: "ПЫЛЕСОСЫ",
    type: "vacuum_product",
    link: "пылесосы",
    isNew: true,
    count: 42,
    singleLink: "пылесос-для-сухой-и-влажной-уборки-nt-70-2",
    popularity: 99
  },
  {
    id: 18,
    title: "Пылесосы",
    description: "Пылесос для сухой уборки T 12/1",
    price: "48000 UZS",
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    category: "ПЫЛЕСОСЫ",
    type: "vacuum_product",
    link: "пылесосы",
    isNew: false,
    count: 42,
    singleLink: "пылесос-для-сухой-уборки-t-12-1",
    popularity: 98
  },
  {
    id: 19,
    title: "Уборочный инвентарь",
    description: "Тележка уборочная двухведерная",
    price: "22000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: false,
    count: 85,
    singleLink: "тележка-уборочная-двухведерная",
    popularity: 96
  },
  {
    id: 20,
    title: "Уборочный инвентарь",
    description: "Держатель мопа складной 40 см",
    price: "15000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: false,
    count: 85,
    singleLink: "держатель-мопа-складной-40-см",
    popularity: 94
  },
  {
    id: 21,
    title: "Уборочный инвентарь",
    description: "Набор для уборки совок и щетка",
    price: "18000 UZS",
    oldPrice: "20000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: true,
    count: 85,
    singleLink: "набор-для-уборки-совок-и-щетка",
    popularity: 92
  },
  {
    id: 22,
    title: "Поломоечные машины",
    description: "T15B",
    price: "100000 UZS",
    image: scrubber,
    images: [scrubber, scrubber, scrubber, scrubber],
    category: "ПОЛОМОЕЧНЫЕ МАШИНЫ",
    type: "scrubber_product",
    link: "поломоечные-машины",
    isNew: false,
    count: 8,
    singleLink: "t15b",
    popularity: 86
  },
  {
    id: 23,
    title: "Поломоечные машины",
    description: "T35B",
    price: "120000 UZS",
    oldPrice: "130000 UZS",
    image: scrubber,
    images: [scrubber, scrubber, scrubber, scrubber],
    category: "ПОЛОМОЕЧНЫЕ МАШИНЫ",
    type: "scrubber_product",
    link: "поломоечные-машины",
    isNew: true,
    count: 8,
    singleLink: "t35b-scrubber",
    popularity: 84
  },
  {
    id: 24,
    title: "Поломоечные машины",
    description: "T45/50B",
    price: "100000 UZS",
    oldPrice: "120000 UZS",
    image: scrubber,
    images: [scrubber, scrubber, scrubber, scrubber],
    category: "ПОЛОМОЕЧНЫЕ МАШИНЫ",
    type: "scrubber_product",
    link: "поломоечные-машины",
    isNew: true,
    count: 8,
    singleLink: "t45-50b-scrubber",
    popularity: 83
  },
  {
    id: 25,
    title: "Поломоечные машины",
    description: "T45E+ (T45/50E)",
    price: "150000 UZS",
    image: scrubber,
    images: [scrubber, scrubber, scrubber, scrubber],
    category: "ПОЛОМОЕЧНЫЕ МАШИНЫ",
    type: "scrubber_product",
    link: "поломоечные-машины",
    isNew: false,
    count: 8,
    singleLink: "t45e-plus",
    popularity: 81
  },
  {
    id: 26,
    title: "Пылесосы",
    description: "Вертикальный пылесос BS 360 sebo",
    price: "85000 UZS",
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    category: "ПЫЛЕСОСЫ",
    type: "vacuum_product",
    link: "пылесосы",
    isNew: false,
    count: 42,
    singleLink: "вертикальный-пылесос-bs-360-sebo",
    popularity: 79
  },
  {
    id: 27,
    title: "Пылесосы",
    description: "Вертикальный пылесос BS 460 sebo",
    price: "95000 UZS",
    oldPrice: "100000 UZS",
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    category: "ПЫЛЕСОСЫ",
    type: "vacuum_product",
    link: "пылесосы",
    isNew: true,
    count: 42,
    singleLink: "вертикальный-пылесос-bs-460-sebo",
    popularity: 77
  },
  {
    id: 28,
    title: "Пылесосы",
    description: "Вертикальный пылесос SEBO AUTOMATIC XP 10",
    price: "120000 UZS",
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    category: "ПЫЛЕСОСЫ",
    type: "vacuum_product",
    link: "пылесосы",
    isNew: false,
    count: 42,
    singleLink: "вертикальный-пылесос-sebo-automatic-xp-10",
    popularity: 76
  },
  {
    id: 29,
    title: "Пылесосы",
    description: "Вертикальный пылесос SEBO AUTOMATIC XP30",
    price: "130000 UZS",
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    category: "ПЫЛЕСОСЫ",
    type: "vacuum_product",
    link: "пылесосы",
    isNew: false,
    count: 42,
    singleLink: "вертикальный-пылесос-sebo-automatic-xp30",
    popularity: 75
  },
  {
    id: 30,
    title: "Пылесосы",
    description: "Вертикальный пылесос SEBO Evolution 350",
    price: "140000 UZS",
    oldPrice: "150000 UZS",
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    category: "ПЫЛЕСОСЫ",
    type: "vacuum_product",
    link: "пылесосы",
    isNew: true,
    count: 42,
    singleLink: "вертикальный-пылесос-sebo-evolution-350",
    popularity: 74
  },
  {
    id: 31,
    title: "Пылесосы",
    description: "Вертикальный пылесос SEBO Evolution 450",
    price: "160000 UZS",
    image: vacum,
    images: [vacum, vacum, vacum, vacum],
    category: "ПЫЛЕСОСЫ",
    type: "vacuum_product",
    link: "пылесосы",
    isNew: false,
    count: 42,
    singleLink: "вертикальный-пылесос-sebo-evolution-450",
    popularity: 73
  },
  {
    id: 32,
    title: "Уборочный инвентарь",
    description: "Держатель мопа TTS Pocket Lampo 00000854YM",
    price: "25000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: false,
    count: 85,
    singleLink: "держатель-мопа-tts-pocket-lampo-00000854ym",
    popularity: 72
  },
  {
    id: 33,
    title: "Уборочный инвентарь",
    description: "Держатель мопа TTS Trilogy 0000770X",
    price: "28000 UZS",
    oldPrice: "30000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: true,
    count: 85,
    singleLink: "держатель-мопа-tts-trilogy-0000770x",
    popularity: 71
  },
  {
    id: 34,
    title: "Уборочный инвентарь",
    description: "Держатель мопа TTS Uni Junior 0000084GV",
    price: "22000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: false,
    count: 85,
    singleLink: "держатель-мопа-tts-uni-junior-0000084gv",
    popularity: 70
  },
  {
    id: 35,
    title: "Уборочный инвентарь",
    description: "Держатель мопа TTS Uni System 0000870",
    price: "26000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: false,
    count: 85,
    singleLink: "держатель-мопа-tts-uni-system-0000870",
    popularity: 69
  },
  {
    id: 36,
    title: "Уборочный инвентарь",
    description: "Держатель мопа TTS Uni System 0000870Y",
    price: "26000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: false,
    count: 85,
    singleLink: "держатель-мопа-tts-uni-system-0000870y",
    popularity: 68
  },
  {
    id: 37,
    title: "Уборочный инвентарь",
    description: "Держатель мопа TTS Uni System Lampo 00000870YM",
    price: "29000 UZS",
    oldPrice: "32000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: true,
    count: 85,
    singleLink: "держатель-мопа-tts-uni-system-lampo-00000870ym",
    popularity: 78
  },
  {
    id: 38,
    title: "Уборочный инвентарь",
    description: "Держатель мопа TTS Velook 0000087EY",
    price: "24000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: false,
    count: 85,
    singleLink: "держатель-мопа-tts-velook-0000087ey",
    popularity: 72
  },
  {
    id: 39,
    title: "Уборочный инвентарь",
    description: "Держатель мопа TTS Wet Disinfection Blik 0000087YE",
    price: "27000 UZS",
    image: equipment,
    images: [equipment, equipment, equipment, equipment],
    category: "УБОРОЧНЫЙ ИНВЕНТАРЬ",
    type: "equipment_product",
    link: "уборочный-инвентарь",
    isNew: false,
    count: 85,
    singleLink: "держатель-мопа-tts-wet-disinfection-blik-0000087ye",
    popularity: 70
  }
];

export const categorySlice = createSlice({
  name: "categories",
  initialState,
  reducers: {
    filterByCategory: (state, action) => {
      return state.filter(item => item.type === action.payload);
    },
    filterByPrice: (state, action) => {
      return state.filter(item => {
        const price = parseInt(item.price.split(' ')[0]);
        return price >= action.payload.min && price <= action.payload.max;
      });
    },
    getProductById: (state, action) => {
      return state.find(item => item.id === action.payload) || null;
    }
  },
});

export const {
  filterByCategory,
  filterByPrice,
  getProductById
} = categorySlice.actions;

export default categorySlice.reducer;
